#! /bin/sh

set -e

font='tandy_9x14'
fps=5

while [ $# != 0 ]; do
    case "$1" in 
        --font)
            font="$2"
            shift
            ;;
        --fps)
            fps="$2"
            shift
            ;;
        *)
            printf '
thorn-to-gif options:

    \33[91m--font \33[0mFONT     set the font to ~/.local/share/thorn/fonts/FONT
    \33[91m--fps  \33[0mFPS      set the fps to FPS
    \33[91m--help \33[0m         show this help message

'
            exit 1
            ;;
    esac
    shift
done

echo $font
echo $fps

thorn-to-ppm --font $font

mkdir ppms || true
mv *.ppm ppms

ffmpeg -i ppms/output%05d.ppm -vf palettegen=max_colors=8 palette.png
ffmpeg                                    \
    -framerate $fps                       \
    -i ppms/output%05d.ppm                \
    -i palette.png                        \
    -lavfi "paletteuse=dither=none"       \
    output.gif 

rm -r ppms palette.png 

