#! /bin/sh

set -e
FONT_DIR="$HOME/.local/share/thorn/fonts/"
FONT='ibm_9x14'
FPS=5

print_help() {
    printf 'thorn-to-gif options:
        --font-dir DIR       Set the font directory to DIR
        --font-name NAME     Set the font to NAME
        --fps FPS            Set the fps to FPS
        --help               Show this help message
    '
    exit 1
}

while [ $# != 0 ]; do
    case "$1" in 
        --font-dir)
            FONT_DIR="$2"
            shift
            ;;
        --font-name)
            FONT="$2"
            shift
            ;;
        --fps)
            FPS="$2"
            shift
            ;;
        --help | -h)
            print_help
            ;;
        *)
            printf "\33[91merror: \33[0munknown option '%s'\n" "$1"
            printf 'use --help to see all options\n'
            exit 1
            ;;
    esac
    shift
done

FONT_PATH="$FONT_DIR/$FONT"

printf "    \033[95mfont-dir   \033[0m$FONT_DIR\n" >&2
printf "    \033[95mfont-name  \033[0m$FONT\n"     >&2
printf "    \033[95mfps        \033[0m$FPS\n"      >&2

temp=$(mktemp -d ppmdirXXXX)

cd $temp
thorn-to-ppm --font $FONT_PATH

ffmpeg -loglevel error -i output%05d.ppm -vf palettegen=max_colors=8 palette.png

ffmpeg                                 \
    -loglevel error                    \
    -framerate $FPS                    \
    -i output%05d.ppm                  \
    -i palette.png                     \
    -lavfi "paletteuse=dither=none"    \
    -f gif                             \
    -

rm -r *.ppm palette.png 
cd ..
rm -r $temp

